# Generated by Django 4.0 on 2021-12-21 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_yazilarmodel'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='yazilarmodel',
            table='Yazi',
        ),
    ]
